version: "3.9"
services:
  guacamole.dev:
    container_name: guacamole.dev
    env_file:
      - .env
    build:
      context: .
      dockerfile: build/guacamole/Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000